repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        types_or: [html, css, markdown]
  - repo: https://github.com/biomejs/pre-commit
    rev: "v0.1.0"
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@1.6.3"]