/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Entities {
  /**
   * The Entity's Cornflake ID
   */
  id?: string;
  /**
   * The Entity's name
   */
  name?: string;
  /**
   * The type of Entity (e.g. 'DISCORD_USER', 'DISCORD_BOT', 'ORGANIZATION')
   */
  type?: "DISCORD_BOT" | "DISCORD_USER" | "ORGANIZATION";
  /**
   * The handle of the entity (ie: @cordx)
   */
  handle?: string;
  /**
   * The biography of the entity
   */
  biography?: string;
  /**
   * The avatar image for the entity
   */
  avatar?: string;
  /**
   * The banner image for the entity
   */
  banner?: string;
  /**
   * The Discord User ID of the entity (if entity is a user)
   */
  userid?: string;
  /**
   * The Discord Client ID of the entity (if entity is a bot)
   */
  botid?: string;
  /**
   * The Discord Webhook URL (if entity has a webhook)
   */
  webhook?: string;
  /**
   * The domain of the entity
   */
  domain?: string;
  /**
   * The API key for the entity
   */
  apiKey?: string;
  /**
   * The owner of the entity (if entity is an organization)
   */
  owner?: string;
  /**
   * The date the entity was created
   */
  createdAt?: string;
  /**
   * The date the entity was last updated
   */
  updatedAt?: string;
  [k: string]: unknown;
}
