/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface EntitiesFileSchema {
  /**
   * The Entity's CordX Cornflake ID
   */
  id?: string;
  /**
   * The type of entity (User, Organization)
   */
  type?: string;
  /**
   * The domain of the entity
   */
  domain?: string;
  _count?: {
    /**
     * The number of domains associated with the entity
     */
    domains?: number;
    /**
     * The number of uploads created by the entity
     */
    uploads?: number;
    /**
     * The number of webhooks associated with the entity
     */
    webhooks?: number;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
